apiVersion: v1
kind: Pod
metadata:
  name: bftest-httpserver
  labels:
    app: bftest-httpserver
spec:
  containers:
    - command:
        - /bin/bash
        - '-c'
        - sleep 100000
      image: 'docker.io/manish2296lion/rootcontainer:latest'
      name: bftest-httpserver
  automountServiceAccountToken: true
